### ISSUE TITLE
uglify fails to parse executable files

### ISSUE THREAD

**Issue by clux** [fishbar/jscoverage#23]
Uglify failes to parse executable files - https://github.com/mishoo/UglifyJS2/issues/509 - that use the shebang directive and thus jscoverage fails.

``` bash
$ jscoverage lib
/home/clux/repos/badgify/node_modules/jscoverage/node_modules/uglify-js/lib/parse.js:204
    throw new JS_Parse_Error(message, line, col, pos);
          ^
Error
    at new JS_Parse_Error (/home/clux/repos/badgify/node_modules/jscoverage/node_modules/uglify-js/lib/parse.js:196:18)
    at js_error (/home/clux/repos/badgify/node_modules/jscoverage/node_modules/uglify-js/lib/parse.js:204:11)
    at parse_error (/home/clux/repos/badgify/node_modules/jscoverage/node_modules/uglify-js/lib/parse.js:306:9)
    at Object.next_token [as input] (/home/clux/repos/badgify/node_modules/jscoverage/node_modules/uglify-js/lib/parse.js:551:9)
    at next (/home/clux/repos/badgify/node_modules/jscoverage/node_modules/uglify-js/lib/parse.js:649:25)
    at Object.parse (/home/clux/repos/badgify/node_modules/jscoverage/node_modules/uglify-js/lib/parse.js:635:15)
    at Object.Instrument.process (/home/clux/repos/badgify/node_modules/jscoverage/lib/instrument.js:60:22)
    at Object.exports.process (/home/clux/repos/badgify/node_modules/jscoverage/lib/jscoverage.js:132:18)
    at Object.exports.processFile (/home/clux/repos/badgify/node_modules/jscoverage/index.js:170:18)
    at /home/clux/repos/badgify/node_modules/jscoverage/bin/jscoverage:63:20
```

jscoverage version 0.5.4

**Comment by fishbar** [comment]
Shebang is not part of  js snytax， seems i can ignore it before pass code to uglify.parse()

i will fix it in this week

**Comment by clux** [comment]
Okay, thank you :]

**Comment by fishbar** [comment]
it's done, update to v0.5.5

**Comment by clux** [comment]
Thanks again. That works perfectly now.
