### ISSUE TITLE
.DS_Store files not ignored, and cause error, on a Mac

### ISSUE THREAD

**Issue by karlbecker** [fishbar/jscoverage#30]
When running jscoverage inside vagrant on my Mac, it threw up this error message:

```
/usr/lib/node_modules/jscoverage/node_modules/uglify-js/lib/parse.js:197
    throw new JS_Parse_Error(message, line, col, pos);
          ^
Error
    at new JS_Parse_Error (/usr/lib/node_modules/jscoverage/node_modules/uglify-js/lib/parse.js:189:18)
    at js_error (/usr/lib/node_modules/jscoverage/node_modules/uglify-js/lib/parse.js:197:11)
    at parse_error (/usr/lib/node_modules/jscoverage/node_modules/uglify-js/lib/parse.js:299:9)
    at Object.next_token [as input] (/usr/lib/node_modules/jscoverage/node_modules/uglify-js/lib/parse.js:544:9)
    at next (/usr/lib/node_modules/jscoverage/node_modules/uglify-js/lib/parse.js:642:25)
    at Object.parse (/usr/lib/node_modules/jscoverage/node_modules/uglify-js/lib/parse.js:628:15)
    at Object.Instrument.process (/usr/lib/node_modules/jscoverage/lib/instrument.js:129:26)
    at Object.exports.process (/usr/lib/node_modules/jscoverage/lib/jscoverage.js:222:20)
    at Object.exports.processFile (/usr/lib/node_modules/jscoverage/index.js:206:18)
    at help (/usr/lib/node_modules/jscoverage/bin/jscoverage:63:20)
```

Turns out jscoverage/lib/instrument.js was inspecting the .DS_Store file inside the source directory.

I believe this is unintentional behavior, and I wonder how many Mac users this bug is biting.

Anyone else have this experience?  This was using a fresh `npm -g install jscoverage` that I installed today.

Thanks!

**Comment by fishbar** [comment]
you should using  `.covignore` file to ignore this file, the same as `.gitignore`

**Comment by fishbar** [comment]
v0.6.0 published, now jscovergae will ignore .DS_Store file
